# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Ailment.create(name: 'Acne')
Ailment.create(name: 'Age Spots')
Ailment.create(name: 'Aging')
Ailment.create(name: 'Allergies')
Ailment.create(name: 'Anemia')
Ailment.create(name: 'Arthritis')
Ailment.create(name: 'Asthma')
Ailment.create(name: 'Atherosclerosis')
Ailment.create(name: 'Backache')
Ailment.create(name: 'Bladder Infection')
Ailment.create(name: 'Bronchitis')
Ailment.create(name: 'Bursitis')
Ailment.create(name: 'Cancer')
Ailment.create(name: 'Candidiasis')
Ailment.create(name: 'Canker Sores')
Ailment.create(name: 'Carpel Tunnel Syndrome')
Ailment.create(name: 'Cataracts')
Ailment.create(name: 'Cellulite')
Ailment.create(name: 'Chronic Fatigue Syndrome')
Ailment.create(name: 'Circulation Problems')
Ailment.create(name: 'Cold Sores/HSV')
Ailment.create(name: 'Colitis')
Ailment.create(name: 'Cold/Flu')
Ailment.create(name: 'Constipation')
Ailment.create(name: 'Crohns')
Ailment.create(name: 'Depression')
Ailment.create(name: 'Diabetes')
Ailment.create(name: 'Diarrhea')
Ailment.create(name: 'Diverticulitis')
Ailment.create(name: 'Eczema')
Ailment.create(name: 'Epilepsy')
Ailment.create(name: 'Gout')
Ailment.create(name: 'Hair Loss')
Ailment.create(name: 'High Blood Pressure/Hypertension')
Ailment.create(name: 'High Cholesterol')
Ailment.create(name: 'Hypoglycemia')
Ailment.create(name: 'Indigestion')
Ailment.create(name: 'Infections')
Ailment.create(name: 'Inflammation')
Ailment.create(name: 'Insomnia')
Ailment.create(name: 'Lyme Disease')
Ailment.create(name: 'Memory Problems')
Ailment.create(name: 'Menopause')
Ailment.create(name: 'Migraine')
Ailment.create(name: 'Motion Sickness')
Ailment.create(name: 'Muscle Cramps')
Ailment.create(name: 'Osteoporosis')
Ailment.create(name: 'Overweight/Obesity')
Ailment.create(name: 'Periodontal Disease')
Ailment.create(name: 'PMS')
Ailment.create(name: 'Psoriasis')
Ailment.create(name: 'Sore Throat')
Ailment.create(name: 'Stress')
Ailment.create(name: 'Surgery Preparation')
Ailment.create(name: 'Thrombosis')
Ailment.create(name: 'Tinnitus')
Ailment.create(name: 'Ulcers')
Ailment.create(name: 'Underweight')
Ailment.create(name: 'Varicose Veins')
Ailment.create(name: 'Water Retention')

# Recipe.create(name: 'Pineapple-Mango Smoothie')
# Recipe.create(name: 'Pineapple-Banana Smoothie')
# Recipe.create(name: 'Pineapple-Orange Smoothie')
# Recipe.create(name: 'Pineapple-Vanilla Smoothie')
# Recipe.create(name: 'Pineapple-Orange-Green Smoothie')
# Recipe.create(name: 'Blueberry-Mango Smoothie')
# Recipe.create(name: 'Blueberry-Apple Smoothie')
# Recipe.create(name: 'Blueberry-Peach Smoothie')
# Recipe.create(name: 'Strawberry-Pear Smoothie')
# Recipe.create(name: 'Straw-Berry-Blast Smoothie')
# Recipe.create(name: 'Strawberry-Watermelon Smoothie')
# Recipe.create(name: 'Strawberry-Peach Smoothie')
# Recipe.create(name: 'Strawberry-Grape Smoothie')
# Recipe.create(name: 'Creamy Lemon-Banana Smoothie')
# Recipe.create(name: 'Lemon-Mint Smoothie')
# Recipe.create(name: 'Strawberry-Lemonade Smoothie')
# Recipe.create(name: 'Tangy Lemon-Mango Smoothie')
# Recipe.create(name: 'Coconut-Peach Smoothie')
# Recipe.create(name: 'Coconut-Mango-Kiwi Smoothie')
# Recipe.create(name: 'Coconut-Banana Smoothie')
# Recipe.create(name: 'Cranberry Apple Smoothie')
# Recipe.create(name: 'Cranberry Grape Smoothie')
# Recipe.create(name: 'Cranberry banana Smoothie')
# Recipe.create(name: 'Ginger-Apple-Papaya Smoothie')
# Recipe.create(name: 'Orange-Ginger-Carrot Smoothie')
# Recipe.create(name: 'Apple-Ginger Smoothie')
# Recipe.create(name: 'Lemon-Ginger Durian Smoothie')
# Recipe.create(name: 'Banana Coconut with Ginger Smoothie')
# Recipe.create(name: 'Pumpkin Pie Smoothie')
# Recipe.create(name: 'Apricot-Ginger Smoothie')
# Recipe.create(name: 'Avocado-Apple Smoothie')
# Recipe.create(name: 'Avocado-Banana Smoothie')
# Recipe.create(name: 'Avocado-Kiwi Smoothie')
# Recipe.create(name: 'Avocado-Berry Fruit Smoothie')
# Recipe.create(name: 'Cucumber-Pear Smoothie')
# Recipe.create(name: 'Cucumber-Melon Smoothie')
# Recipe.create(name: 'Cucumber-Cantaloupe Smoothie')
# Recipe.create(name: 'Apple-Lemon Smoothie')
# Recipe.create(name: 'Apple-Grape Smoothie')
# Recipe.create(name: 'Apple-Pear-Banana Smoothie')
# Recipe.create(name: 'Apple-Blueberry Smoothie')
# Recipe.create(name: 'Apple-Green Smoothie')






# ailment_list = [
# ["Acne"],
# ["Age Spots"],
# ["Aging"]
# ]

# ailment_list.each do |name|
# 	Ailment.create(name: name)
# end